Linear Algebra with Numpy

In [1]:
import numpy as np

In [2]:
alist=[1,2,3,4,5]
narray=np.array([1,2,3,4])

In [3]:
print(narray+narray) #Numpy arrays add element wise
print (alist+alist) #list concatenates

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
npmatrix1=np.array([narray,narray,narray])
print(npmatrix1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [5]:
print(npmatrix1*2)

[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]


In [7]:
print(npmatrix1.T)
#transpose does not work on 1d array
print(narray.T)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
[1 2 3 4]


In [9]:
#norm of a nparray or matrix
nparray1=np.array([1,2,3,4])
norm1=np.linalg.norm(nparray1)

nparray2=np.array([[1,2],[3,4]])
norm2=np.linalg.norm(nparray2)

print(norm1)
print(norm2)


5.477225575051661
5.477225575051661


In [10]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) 

normByCols = np.linalg.norm(nparray2, axis=0) 
normByRows = np.linalg.norm(nparray2, axis=1) 

print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [11]:
#dot product: takes two vectors and returns a single number
dotp=np.dot(narray,narray)
print(dotp)
#dot product of nparrays is equal to dot product of python lists

30


In [13]:
nparray2=np.array([[1,-1],[2,-2],[3,-3]])
sumByCols=np.sum(nparray2,axis=0)
mean=np.mean(nparray2,axis=0)
sumByRows = np.sum(nparray2, axis=1)
print(sumByCols)
print(mean)
print(sumByRows)

[ 6 -6]
[ 2. -2.]
[0 0 0]
